# -*- coding: utf-8 -*-
"""Apples-and-Oranges.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CUt03jHOHwWiUaW7n1fiKT6WHz0QSgyX
"""

redcolor=0
smooth=0
apple=0

orangecolor=1
rough=1
orange=1

#Put all data points in an array - features and labels in seperate arrays

features=[[redcolor,smooth],[orangecolor,rough],[redcolor,smooth],[redcolor,smooth],[orangecolor,rough],[orangecolor,rough],[redcolor,smooth]]

labels=[apple,orange,apple,apple,orange,orange,apple]

#import decision tree function from sklearn package and train it on your data

from sklearn import tree

classifier=tree.DecisionTreeClassifier()
classifier.fit(features,labels)

inputcolor=input('Enter the color of the fruit: ')
inputtexture=input('Enter the texture of the fruit: ')

if (inputcolor == 'red' or inputcolor == 'redcolor'):
  inputcolornew = 0
else:
  inputcolornew = 1
if (inputtexture =='smooth'):
  inputtexturenew = 0
else:
  inputtexturenew = 1

#predict output for user's input and print output

if(classifier.predict([[inputcolornew,inputtexturenew]]) == 0):
  print('Fruit is an Apple')
else:
  print('Fruit is an Orange')